name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-18.04
    name: Linting
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup node v12
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run style-check

      - name: Lint
        run: npm run lint
